### ISSUE TITLE
`core` cleanup todo

### ISSUE THREAD

**Issue by consol3cowboy** [defidotmoney/dfm-contracts#21]
Misc minor edits to make prior to launch, to improve consistency between the contracts.

`PriceKeeperRegulator`
 - [x] rename `AGGREGATOR` to `PRICE_ORACLE` (or `STABLECOIN_PRICE_ORACLE`?)
 
`PegKeeper`
 - [x] rename `PEGGED` to `STABLECOIN`
 - [x]  reorder storage vars

`AMM`
 - [x]  rename `BORROWED_TOKEN` to `STABLECOIN`
 
`AggMonetaryPolicy2`
 - [x]  remove 2 from title
 - [x]  move to `monetary_policies/` subfolder

`AggregateStablePrice`
 - [x]  reorganize functions
 - [ ]  rename contract?
